# FreqHub Strategies - Curated Strategies for Freqtrade to be used with FreqHub
# Copyright (C) 2025 - 2026  FreqHub Strategies Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ⚖️ DISCLAIMER
# USE AT YOUR OWN RISK
#
# This software is provided "as is", without warranty of any kind, express or implied,
# including but not limited to the warranties of merchantability, fitness for a particular
# purpose and noninfringement. In no event shall the authors or copyright holders be liable
# for any claim, damages or other liability, whether in an action of contract, tort or
# otherwise, arising from, out of or in connection with the software or the use or other
# dealings in the software.
#
# Trading cryptocurrencies involves substantial risk of loss and is not suitable for every
# investor. The value of cryptocurrencies may fluctuate, and you may lose some or all of
# your investment. Past performance is not indicative of future results.

name: freqhub-stack

services:
  freqtrade-markov-fastema-hyperopt:
    build: .
    image: freqhub-strategy-markov-fastema:latest
    container_name: freqtrade-markov-fastema-hyperopt
    restart: "no"
    volumes:
      - ./config.json:/freqtrade/user_data/config.json:ro
      - ./user_data/data:/freqtrade/user_data/data
      - ./user_data/logs:/freqtrade/user_data/logs
    environment:
      - FREQTRADE__EXCHANGE__NAME=${FREQTRADE_EXCHANGE_NAME:-binance}
      - FREQTRADE__EXCHANGE__KEY=${FREQTRADE_EXCHANGE_KEY_1:-}
      - FREQTRADE__EXCHANGE__SECRET=${FREQTRADE_EXCHANGE_SECRET_1:-}
      - FREQTRADE__DRY_RUN=${FREQTRADE_DRY_RUN:-true}
      - FREQTRADE__DRY_RUN_WALLET=${FREQTRADE_DRY_RUN_WALLET:-1000}
      - FREQTRADE__STRATEGY=MarkovFastEMAStrategy
      - FREQTRADE_HYPEROPT_EPOCHS=${FREQTRADE_HYPEROPT_EPOCHS:-200}
      - FREQTRADE_HYPEROPT_TIMERANGE=${FREQTRADE_HYPEROPT_TIMERANGE:-20230101-}
    command: >
      hyperopt
      --logfile /freqtrade/user_data/logs/freqtrade-hyperopt.log
      --config /freqtrade/user_data/config.json
      --strategy MarkovFastEMAStrategy
      --hyperopt-loss SharpeHyperOptLoss
      --spaces buy sell
      -e ${FREQTRADE_HYPEROPT_EPOCHS}
      --timerange ${FREQTRADE_HYPEROPT_TIMERANGE}
    networks:
      - freqtrade-network

networks:
  freqtrade-network:
    external: true
